// Code generated by protoc-gen-go.
// source: GtReq.proto
// DO NOT EDIT!

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	GtReq.proto

It has these top-level messages:
	GtAuth
	GtAuthResult
	ReqServList
	ReqServListResult
	PushListResult
	PushResult
	PushOSSingleMessage
	PushMMPSingleMessage
	StartMMPBatchTask
	StartOSBatchTask
	PushListMessage
	EndBatchTask
	PushMMPAppMessage
	ServerNotify
	ServerNotifyResult
	OSMessage
	MMPMessage
	Transparent
	PushInfo
	ActionChain
	AppStartUp
	Button
	Target
*/
package protobuf

import proto "github.com/golang/protobuf/proto"
import "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type CmdID int32

const (
	CmdID_GTHEARDBT            CmdID = 0
	CmdID_GTAUTH               CmdID = 1
	CmdID_GTAUTH_RESULT        CmdID = 2
	CmdID_REQSERVHOST          CmdID = 3
	CmdID_REQSERVHOSTRESULT    CmdID = 4
	CmdID_PUSHRESULT           CmdID = 5
	CmdID_PUSHOSSINGLEMESSAGE  CmdID = 6
	CmdID_PUSHMMPSINGLEMESSAGE CmdID = 7
	CmdID_STARTMMPBATCHTASK    CmdID = 8
	CmdID_STARTOSBATCHTASK     CmdID = 9
	CmdID_PUSHLISTMESSAGE      CmdID = 10
	CmdID_ENDBATCHTASK         CmdID = 11
	CmdID_PUSHMMPAPPMESSAGE    CmdID = 12
	CmdID_SERVERNOTIFY         CmdID = 13
	CmdID_PUSHLISTRESULT       CmdID = 14
	CmdID_SERVERNOTIFYRESULT   CmdID = 15
)

var CmdID_name = map[int32]string{
	0:  "GTHEARDBT",
	1:  "GTAUTH",
	2:  "GTAUTH_RESULT",
	3:  "REQSERVHOST",
	4:  "REQSERVHOSTRESULT",
	5:  "PUSHRESULT",
	6:  "PUSHOSSINGLEMESSAGE",
	7:  "PUSHMMPSINGLEMESSAGE",
	8:  "STARTMMPBATCHTASK",
	9:  "STARTOSBATCHTASK",
	10: "PUSHLISTMESSAGE",
	11: "ENDBATCHTASK",
	12: "PUSHMMPAPPMESSAGE",
	13: "SERVERNOTIFY",
	14: "PUSHLISTRESULT",
	15: "SERVERNOTIFYRESULT",
}
var CmdID_value = map[string]int32{
	"GTHEARDBT":            0,
	"GTAUTH":               1,
	"GTAUTH_RESULT":        2,
	"REQSERVHOST":          3,
	"REQSERVHOSTRESULT":    4,
	"PUSHRESULT":           5,
	"PUSHOSSINGLEMESSAGE":  6,
	"PUSHMMPSINGLEMESSAGE": 7,
	"STARTMMPBATCHTASK":    8,
	"STARTOSBATCHTASK":     9,
	"PUSHLISTMESSAGE":      10,
	"ENDBATCHTASK":         11,
	"PUSHMMPAPPMESSAGE":    12,
	"SERVERNOTIFY":         13,
	"PUSHLISTRESULT":       14,
	"SERVERNOTIFYRESULT":   15,
}

func (x CmdID) Enum() *CmdID {
	p := new(CmdID)
	*p = x
	return p
}
func (x CmdID) String() string {
	return proto.EnumName(CmdID_name, int32(x))
}
func (x *CmdID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CmdID_value, data, "CmdID")
	if err != nil {
		return err
	}
	*x = CmdID(value)
	return nil
}

// 手机短信状态
type SMSStatus int32

const (
	SMSStatus_unread SMSStatus = 0
	SMSStatus_read   SMSStatus = 1
)

var SMSStatus_name = map[int32]string{
	0: "unread",
	1: "read",
}
var SMSStatus_value = map[string]int32{
	"unread": 0,
	"read":   1,
}

func (x SMSStatus) Enum() *SMSStatus {
	p := new(SMSStatus)
	*p = x
	return p
}
func (x SMSStatus) String() string {
	return proto.EnumName(SMSStatus_name, int32(x))
}
func (x *SMSStatus) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SMSStatus_value, data, "SMSStatus")
	if err != nil {
		return err
	}
	*x = SMSStatus(value)
	return nil
}

type GtAuthResult_GtAuthResultCode int32

const (
	GtAuthResult_successed          GtAuthResult_GtAuthResultCode = 0
	GtAuthResult_failed_noSign      GtAuthResult_GtAuthResultCode = 1
	GtAuthResult_failed_noAppkey    GtAuthResult_GtAuthResultCode = 2
	GtAuthResult_failed_noTimestamp GtAuthResult_GtAuthResultCode = 3
	GtAuthResult_failed_AuthIllegal GtAuthResult_GtAuthResultCode = 4
	GtAuthResult_redirect           GtAuthResult_GtAuthResultCode = 5
)

var GtAuthResult_GtAuthResultCode_name = map[int32]string{
	0: "successed",
	1: "failed_noSign",
	2: "failed_noAppkey",
	3: "failed_noTimestamp",
	4: "failed_AuthIllegal",
	5: "redirect",
}
var GtAuthResult_GtAuthResultCode_value = map[string]int32{
	"successed":          0,
	"failed_noSign":      1,
	"failed_noAppkey":    2,
	"failed_noTimestamp": 3,
	"failed_AuthIllegal": 4,
	"redirect":           5,
}

func (x GtAuthResult_GtAuthResultCode) Enum() *GtAuthResult_GtAuthResultCode {
	p := new(GtAuthResult_GtAuthResultCode)
	*p = x
	return p
}
func (x GtAuthResult_GtAuthResultCode) String() string {
	return proto.EnumName(GtAuthResult_GtAuthResultCode_name, int32(x))
}
func (x *GtAuthResult_GtAuthResultCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GtAuthResult_GtAuthResultCode_value, data, "GtAuthResult_GtAuthResultCode")
	if err != nil {
		return err
	}
	*x = GtAuthResult_GtAuthResultCode(value)
	return nil
}

type ReqServListResult_ReqServHostResultCode int32

const (
	// 获取服务器成功
	ReqServListResult_successed ReqServListResult_ReqServHostResultCode = 0
	// 获取服务器异常
	ReqServListResult_failed ReqServListResult_ReqServHostResultCode = 1
	// 当前服务器均忙
	ReqServListResult_busy ReqServListResult_ReqServHostResultCode = 2
)

var ReqServListResult_ReqServHostResultCode_name = map[int32]string{
	0: "successed",
	1: "failed",
	2: "busy",
}
var ReqServListResult_ReqServHostResultCode_value = map[string]int32{
	"successed": 0,
	"failed":    1,
	"busy":      2,
}

func (x ReqServListResult_ReqServHostResultCode) Enum() *ReqServListResult_ReqServHostResultCode {
	p := new(ReqServListResult_ReqServHostResultCode)
	*p = x
	return p
}
func (x ReqServListResult_ReqServHostResultCode) String() string {
	return proto.EnumName(ReqServListResult_ReqServHostResultCode_name, int32(x))
}
func (x *ReqServListResult_ReqServHostResultCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ReqServListResult_ReqServHostResultCode_value, data, "ReqServListResult_ReqServHostResultCode")
	if err != nil {
		return err
	}
	*x = ReqServListResult_ReqServHostResultCode(value)
	return nil
}

type PushResult_EPushResult int32

const (
	// 推送成功
	PushResult_successed_online PushResult_EPushResult = 0
	// 进离线
	PushResult_successed_offline PushResult_EPushResult = 1
	// N天内未登录，放弃下发
	PushResult_successed_ignore PushResult_EPushResult = 2
	// 推送失败，具体原因看info
	PushResult_failed PushResult_EPushResult = 3
	// 服务器忙，客户端等待5分钟后再次尝试
	PushResult_busy PushResult_EPushResult = 4
	// startBatch 成功
	PushResult_success_startBatch PushResult_EPushResult = 5
	// endBatch 成功
	PushResult_success_endBatch PushResult_EPushResult = 6
)

var PushResult_EPushResult_name = map[int32]string{
	0: "successed_online",
	1: "successed_offline",
	2: "successed_ignore",
	3: "failed",
	4: "busy",
	5: "success_startBatch",
	6: "success_endBatch",
}
var PushResult_EPushResult_value = map[string]int32{
	"successed_online":   0,
	"successed_offline":  1,
	"successed_ignore":   2,
	"failed":             3,
	"busy":               4,
	"success_startBatch": 5,
	"success_endBatch":   6,
}

func (x PushResult_EPushResult) Enum() *PushResult_EPushResult {
	p := new(PushResult_EPushResult)
	*p = x
	return p
}
func (x PushResult_EPushResult) String() string {
	return proto.EnumName(PushResult_EPushResult_name, int32(x))
}
func (x *PushResult_EPushResult) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PushResult_EPushResult_value, data, "PushResult_EPushResult")
	if err != nil {
		return err
	}
	*x = PushResult_EPushResult(value)
	return nil
}

type ServerNotify_NotifyType int32

const (
	ServerNotify_normal            ServerNotify_NotifyType = 0
	ServerNotify_serverListChanged ServerNotify_NotifyType = 1
	ServerNotify_exception         ServerNotify_NotifyType = 2
)

var ServerNotify_NotifyType_name = map[int32]string{
	0: "normal",
	1: "serverListChanged",
	2: "exception",
}
var ServerNotify_NotifyType_value = map[string]int32{
	"normal":            0,
	"serverListChanged": 1,
	"exception":         2,
}

func (x ServerNotify_NotifyType) Enum() *ServerNotify_NotifyType {
	p := new(ServerNotify_NotifyType)
	*p = x
	return p
}
func (x ServerNotify_NotifyType) String() string {
	return proto.EnumName(ServerNotify_NotifyType_name, int32(x))
}
func (x *ServerNotify_NotifyType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ServerNotify_NotifyType_value, data, "ServerNotify_NotifyType")
	if err != nil {
		return err
	}
	*x = ServerNotify_NotifyType(value)
	return nil
}

type ActionChain_Type int32

const (
	ActionChain_Goto               ActionChain_Type = 0
	ActionChain_notification       ActionChain_Type = 1
	ActionChain_popup              ActionChain_Type = 2
	ActionChain_startapp           ActionChain_Type = 3
	ActionChain_startweb           ActionChain_Type = 4
	ActionChain_smsinbox           ActionChain_Type = 5
	ActionChain_checkapp           ActionChain_Type = 6
	ActionChain_eoa                ActionChain_Type = 7
	ActionChain_appdownload        ActionChain_Type = 8
	ActionChain_startsms           ActionChain_Type = 9
	ActionChain_httpproxy          ActionChain_Type = 10
	ActionChain_smsinbox2          ActionChain_Type = 11
	ActionChain_mmsinbox2          ActionChain_Type = 12
	ActionChain_popupweb           ActionChain_Type = 13
	ActionChain_dial               ActionChain_Type = 14
	ActionChain_reportbindapp      ActionChain_Type = 15
	ActionChain_reportaddphoneinfo ActionChain_Type = 16
	ActionChain_reportapplist      ActionChain_Type = 17
	ActionChain_terminatetask      ActionChain_Type = 18
	ActionChain_reportapp          ActionChain_Type = 19
	ActionChain_enablelog          ActionChain_Type = 20
	ActionChain_disablelog         ActionChain_Type = 21
	ActionChain_uploadlog          ActionChain_Type = 22
)

var ActionChain_Type_name = map[int32]string{
	0:  "Goto",
	1:  "notification",
	2:  "popup",
	3:  "startapp",
	4:  "startweb",
	5:  "smsinbox",
	6:  "checkapp",
	7:  "eoa",
	8:  "appdownload",
	9:  "startsms",
	10: "httpproxy",
	11: "smsinbox2",
	12: "mmsinbox2",
	13: "popupweb",
	14: "dial",
	15: "reportbindapp",
	16: "reportaddphoneinfo",
	17: "reportapplist",
	18: "terminatetask",
	19: "reportapp",
	20: "enablelog",
	21: "disablelog",
	22: "uploadlog",
}
var ActionChain_Type_value = map[string]int32{
	"Goto":               0,
	"notification":       1,
	"popup":              2,
	"startapp":           3,
	"startweb":           4,
	"smsinbox":           5,
	"checkapp":           6,
	"eoa":                7,
	"appdownload":        8,
	"startsms":           9,
	"httpproxy":          10,
	"smsinbox2":          11,
	"mmsinbox2":          12,
	"popupweb":           13,
	"dial":               14,
	"reportbindapp":      15,
	"reportaddphoneinfo": 16,
	"reportapplist":      17,
	"terminatetask":      18,
	"reportapp":          19,
	"enablelog":          20,
	"disablelog":         21,
	"uploadlog":          22,
}

func (x ActionChain_Type) Enum() *ActionChain_Type {
	p := new(ActionChain_Type)
	*p = x
	return p
}
func (x ActionChain_Type) String() string {
	return proto.EnumName(ActionChain_Type_name, int32(x))
}
func (x *ActionChain_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ActionChain_Type_value, data, "ActionChain_Type")
	if err != nil {
		return err
	}
	*x = ActionChain_Type(value)
	return nil
}

// 校验指令，指令号0x01
type GtAuth struct {
	Sign             *string `protobuf:"bytes,1,req,name=sign" json:"sign,omitempty"`
	Appkey           *string `protobuf:"bytes,2,req,name=appkey" json:"appkey,omitempty"`
	Timestamp        *int64  `protobuf:"varint,3,req,name=timestamp" json:"timestamp,omitempty"`
	SeqId            *string `protobuf:"bytes,4,opt,name=seqId" json:"seqId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GtAuth) Reset()         { *m = GtAuth{} }
func (m *GtAuth) String() string { return proto.CompactTextString(m) }
func (*GtAuth) ProtoMessage()    {}

func (m *GtAuth) GetSign() string {
	if m != nil && m.Sign != nil {
		return *m.Sign
	}
	return ""
}

func (m *GtAuth) GetAppkey() string {
	if m != nil && m.Appkey != nil {
		return *m.Appkey
	}
	return ""
}

func (m *GtAuth) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *GtAuth) GetSeqId() string {
	if m != nil && m.SeqId != nil {
		return *m.SeqId
	}
	return ""
}

// 校验返回结果，指令号0x02
type GtAuthResult struct {
	Code             *int32  `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	RedirectAddress  *string `protobuf:"bytes,2,opt,name=redirectAddress" json:"redirectAddress,omitempty"`
	SeqId            *string `protobuf:"bytes,3,opt,name=seqId" json:"seqId,omitempty"`
	Info             *string `protobuf:"bytes,4,opt,name=info" json:"info,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GtAuthResult) Reset()         { *m = GtAuthResult{} }
func (m *GtAuthResult) String() string { return proto.CompactTextString(m) }
func (*GtAuthResult) ProtoMessage()    {}

func (m *GtAuthResult) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *GtAuthResult) GetRedirectAddress() string {
	if m != nil && m.RedirectAddress != nil {
		return *m.RedirectAddress
	}
	return ""
}

func (m *GtAuthResult) GetSeqId() string {
	if m != nil && m.SeqId != nil {
		return *m.SeqId
	}
	return ""
}

func (m *GtAuthResult) GetInfo() string {
	if m != nil && m.Info != nil {
		return *m.Info
	}
	return ""
}

// 获得服务器地址指令，指令号0x03
type ReqServList struct {
	SeqId            *string `protobuf:"bytes,1,opt,name=seqId" json:"seqId,omitempty"`
	Timestamp        *int64  `protobuf:"varint,3,req,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ReqServList) Reset()         { *m = ReqServList{} }
func (m *ReqServList) String() string { return proto.CompactTextString(m) }
func (*ReqServList) ProtoMessage()    {}

func (m *ReqServList) GetSeqId() string {
	if m != nil && m.SeqId != nil {
		return *m.SeqId
	}
	return ""
}

func (m *ReqServList) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

// 服务器地址返回结果，指令号0x04
type ReqServListResult struct {
	Code *int32 `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	// 返回的服务器列表信息(格式为："ip:port")
	Host             []string `protobuf:"bytes,2,rep,name=host" json:"host,omitempty"`
	SeqId            *string  `protobuf:"bytes,3,opt,name=seqId" json:"seqId,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ReqServListResult) Reset()         { *m = ReqServListResult{} }
func (m *ReqServListResult) String() string { return proto.CompactTextString(m) }
func (*ReqServListResult) ProtoMessage()    {}

func (m *ReqServListResult) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *ReqServListResult) GetHost() []string {
	if m != nil {
		return m.Host
	}
	return nil
}

func (m *ReqServListResult) GetSeqId() string {
	if m != nil && m.SeqId != nil {
		return *m.SeqId
	}
	return ""
}

// 批量推送结果，指令号0x0E
type PushListResult struct {
	Results          []*PushResult `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *PushListResult) Reset()         { *m = PushListResult{} }
func (m *PushListResult) String() string { return proto.CompactTextString(m) }
func (*PushListResult) ProtoMessage()    {}

func (m *PushListResult) GetResults() []*PushResult {
	if m != nil {
		return m.Results
	}
	return nil
}

// 推送结果，指令号0x05
type PushResult struct {
	Result           *PushResult_EPushResult `protobuf:"varint,1,req,name=result,enum=protobuf.PushResult_EPushResult" json:"result,omitempty"`
	TaskId           *string                 `protobuf:"bytes,2,req,name=taskId" json:"taskId,omitempty"`
	MessageId        *string                 `protobuf:"bytes,3,req,name=messageId" json:"messageId,omitempty"`
	SeqId            *string                 `protobuf:"bytes,4,req,name=seqId" json:"seqId,omitempty"`
	Target           *string                 `protobuf:"bytes,5,req,name=target" json:"target,omitempty"`
	Info             *string                 `protobuf:"bytes,6,opt,name=info" json:"info,omitempty"`
	TraceId          *string                 `protobuf:"bytes,7,opt,name=traceId" json:"traceId,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *PushResult) Reset()         { *m = PushResult{} }
func (m *PushResult) String() string { return proto.CompactTextString(m) }
func (*PushResult) ProtoMessage()    {}

func (m *PushResult) GetResult() PushResult_EPushResult {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return PushResult_successed_online
}

func (m *PushResult) GetTaskId() string {
	if m != nil && m.TaskId != nil {
		return *m.TaskId
	}
	return ""
}

func (m *PushResult) GetMessageId() string {
	if m != nil && m.MessageId != nil {
		return *m.MessageId
	}
	return ""
}

func (m *PushResult) GetSeqId() string {
	if m != nil && m.SeqId != nil {
		return *m.SeqId
	}
	return ""
}

func (m *PushResult) GetTarget() string {
	if m != nil && m.Target != nil {
		return *m.Target
	}
	return ""
}

func (m *PushResult) GetInfo() string {
	if m != nil && m.Info != nil {
		return *m.Info
	}
	return ""
}

func (m *PushResult) GetTraceId() string {
	if m != nil && m.TraceId != nil {
		return *m.TraceId
	}
	return ""
}

// 单推给OS，指令号0x06
type PushOSSingleMessage struct {
	// 消息ID，至少保证一个月内不重复
	SeqId *string `protobuf:"bytes,1,req,name=seqId" json:"seqId,omitempty"`
	// 消息体
	Message *OSMessage `protobuf:"bytes,2,req,name=message" json:"message,omitempty"`
	// 接收人信息
	Target           *Target `protobuf:"bytes,3,req,name=target" json:"target,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PushOSSingleMessage) Reset()         { *m = PushOSSingleMessage{} }
func (m *PushOSSingleMessage) String() string { return proto.CompactTextString(m) }
func (*PushOSSingleMessage) ProtoMessage()    {}

func (m *PushOSSingleMessage) GetSeqId() string {
	if m != nil && m.SeqId != nil {
		return *m.SeqId
	}
	return ""
}

func (m *PushOSSingleMessage) GetMessage() *OSMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *PushOSSingleMessage) GetTarget() *Target {
	if m != nil {
		return m.Target
	}
	return nil
}

// 单推给MMP，指令号0x07
type PushMMPSingleMessage struct {
	// 消息ID，至少保证一个月内不重复
	SeqId *string `protobuf:"bytes,1,req,name=seqId" json:"seqId,omitempty"`
	// 消息体
	Message *MMPMessage `protobuf:"bytes,2,req,name=message" json:"message,omitempty"`
	// 接收人信息
	Target           *Target `protobuf:"bytes,3,req,name=target" json:"target,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PushMMPSingleMessage) Reset()         { *m = PushMMPSingleMessage{} }
func (m *PushMMPSingleMessage) String() string { return proto.CompactTextString(m) }
func (*PushMMPSingleMessage) ProtoMessage()    {}

func (m *PushMMPSingleMessage) GetSeqId() string {
	if m != nil && m.SeqId != nil {
		return *m.SeqId
	}
	return ""
}

func (m *PushMMPSingleMessage) GetMessage() *MMPMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *PushMMPSingleMessage) GetTarget() *Target {
	if m != nil {
		return m.Target
	}
	return nil
}

// ------- List群发指令 -----
// 上传群发内容，指令号0x08
type StartMMPBatchTask struct {
	Message *MMPMessage `protobuf:"bytes,1,req,name=message" json:"message,omitempty"`
	// 群发内容超时时间（单位小时），默认为3天
	Expire           *int64  `protobuf:"varint,2,req,name=expire,def=72" json:"expire,omitempty"`
	SeqId            *string `protobuf:"bytes,3,opt,name=seqId" json:"seqId,omitempty"`
	TaskGroupName    *string `protobuf:"bytes,4,opt,name=taskGroupName" json:"taskGroupName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *StartMMPBatchTask) Reset()         { *m = StartMMPBatchTask{} }
func (m *StartMMPBatchTask) String() string { return proto.CompactTextString(m) }
func (*StartMMPBatchTask) ProtoMessage()    {}

const Default_StartMMPBatchTask_Expire int64 = 72

func (m *StartMMPBatchTask) GetMessage() *MMPMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *StartMMPBatchTask) GetExpire() int64 {
	if m != nil && m.Expire != nil {
		return *m.Expire
	}
	return Default_StartMMPBatchTask_Expire
}

func (m *StartMMPBatchTask) GetSeqId() string {
	if m != nil && m.SeqId != nil {
		return *m.SeqId
	}
	return ""
}

func (m *StartMMPBatchTask) GetTaskGroupName() string {
	if m != nil && m.TaskGroupName != nil {
		return *m.TaskGroupName
	}
	return ""
}

// 上传群发内容，指令号0x09
type StartOSBatchTask struct {
	Message *OSMessage `protobuf:"bytes,1,req,name=message" json:"message,omitempty"`
	// 群发内容超时时间（单位小时），默认为3天
	Expire           *int64 `protobuf:"varint,2,req,name=expire,def=72" json:"expire,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *StartOSBatchTask) Reset()         { *m = StartOSBatchTask{} }
func (m *StartOSBatchTask) String() string { return proto.CompactTextString(m) }
func (*StartOSBatchTask) ProtoMessage()    {}

const Default_StartOSBatchTask_Expire int64 = 72

func (m *StartOSBatchTask) GetMessage() *OSMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *StartOSBatchTask) GetExpire() int64 {
	if m != nil && m.Expire != nil {
		return *m.Expire
	}
	return Default_StartOSBatchTask_Expire
}

// 通过上传内容获得的taskId，群发消息，指令号0x0A
type PushListMessage struct {
	// 消息ID，至少保证一个月内不重复
	SeqId *string `protobuf:"bytes,1,req,name=seqId" json:"seqId,omitempty"`
	// 消息任务ID
	TaskId *string `protobuf:"bytes,2,req,name=taskId" json:"taskId,omitempty"`
	// 目标用户, 不超过500个用户
	Targets          []*Target `protobuf:"bytes,3,rep,name=targets" json:"targets,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *PushListMessage) Reset()         { *m = PushListMessage{} }
func (m *PushListMessage) String() string { return proto.CompactTextString(m) }
func (*PushListMessage) ProtoMessage()    {}

func (m *PushListMessage) GetSeqId() string {
	if m != nil && m.SeqId != nil {
		return *m.SeqId
	}
	return ""
}

func (m *PushListMessage) GetTaskId() string {
	if m != nil && m.TaskId != nil {
		return *m.TaskId
	}
	return ""
}

func (m *PushListMessage) GetTargets() []*Target {
	if m != nil {
		return m.Targets
	}
	return nil
}

// 清除群发内容，指令号0x0B
type EndBatchTask struct {
	TaskId           *string `protobuf:"bytes,1,req,name=taskId" json:"taskId,omitempty"`
	SeqId            *string `protobuf:"bytes,2,opt,name=seqId" json:"seqId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *EndBatchTask) Reset()         { *m = EndBatchTask{} }
func (m *EndBatchTask) String() string { return proto.CompactTextString(m) }
func (*EndBatchTask) ProtoMessage()    {}

func (m *EndBatchTask) GetTaskId() string {
	if m != nil && m.TaskId != nil {
		return *m.TaskId
	}
	return ""
}

func (m *EndBatchTask) GetSeqId() string {
	if m != nil && m.SeqId != nil {
		return *m.SeqId
	}
	return ""
}

// ------ APP群发指令 ------
// APP群发指令，指令号0x0C
type PushMMPAppMessage struct {
	Message          *MMPMessage `protobuf:"bytes,1,req,name=message" json:"message,omitempty"`
	AppIdList        []string    `protobuf:"bytes,2,rep,name=appIdList" json:"appIdList,omitempty"`
	PhoneTypeList    []string    `protobuf:"bytes,3,rep,name=phoneTypeList" json:"phoneTypeList,omitempty"`
	ProvinceList     []string    `protobuf:"bytes,4,rep,name=provinceList" json:"provinceList,omitempty"`
	SeqId            *string     `protobuf:"bytes,5,opt,name=seqId" json:"seqId,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *PushMMPAppMessage) Reset()         { *m = PushMMPAppMessage{} }
func (m *PushMMPAppMessage) String() string { return proto.CompactTextString(m) }
func (*PushMMPAppMessage) ProtoMessage()    {}

func (m *PushMMPAppMessage) GetMessage() *MMPMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *PushMMPAppMessage) GetAppIdList() []string {
	if m != nil {
		return m.AppIdList
	}
	return nil
}

func (m *PushMMPAppMessage) GetPhoneTypeList() []string {
	if m != nil {
		return m.PhoneTypeList
	}
	return nil
}

func (m *PushMMPAppMessage) GetProvinceList() []string {
	if m != nil {
		return m.ProvinceList
	}
	return nil
}

func (m *PushMMPAppMessage) GetSeqId() string {
	if m != nil && m.SeqId != nil {
		return *m.SeqId
	}
	return ""
}

// 服务器主动通知指令，指令号0x0D
type ServerNotify struct {
	Type             *ServerNotify_NotifyType `protobuf:"varint,1,req,name=type,enum=protobuf.ServerNotify_NotifyType" json:"type,omitempty"`
	Info             *string                  `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
	Extradata        []byte                   `protobuf:"bytes,3,opt,name=extradata" json:"extradata,omitempty"`
	SeqId            *string                  `protobuf:"bytes,4,opt,name=seqId" json:"seqId,omitempty"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (m *ServerNotify) Reset()         { *m = ServerNotify{} }
func (m *ServerNotify) String() string { return proto.CompactTextString(m) }
func (*ServerNotify) ProtoMessage()    {}

func (m *ServerNotify) GetType() ServerNotify_NotifyType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ServerNotify_normal
}

func (m *ServerNotify) GetInfo() string {
	if m != nil && m.Info != nil {
		return *m.Info
	}
	return ""
}

func (m *ServerNotify) GetExtradata() []byte {
	if m != nil {
		return m.Extradata
	}
	return nil
}

func (m *ServerNotify) GetSeqId() string {
	if m != nil && m.SeqId != nil {
		return *m.SeqId
	}
	return ""
}

// 第三方响应服务器主通知指令，指令号0x0F
type ServerNotifyResult struct {
	SeqId            *string `protobuf:"bytes,1,req,name=seqId" json:"seqId,omitempty"`
	Info             *string `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ServerNotifyResult) Reset()         { *m = ServerNotifyResult{} }
func (m *ServerNotifyResult) String() string { return proto.CompactTextString(m) }
func (*ServerNotifyResult) ProtoMessage()    {}

func (m *ServerNotifyResult) GetSeqId() string {
	if m != nil && m.SeqId != nil {
		return *m.SeqId
	}
	return ""
}

func (m *ServerNotifyResult) GetInfo() string {
	if m != nil && m.Info != nil {
		return *m.Info
	}
	return ""
}

type OSMessage struct {
	// 是否存入离线
	IsOffline *bool `protobuf:"varint,2,req,name=isOffline" json:"isOffline,omitempty"`
	// 离线超时时间（单位小时），默认为1小时
	OfflineExpireTime *int64 `protobuf:"varint,3,req,name=offlineExpireTime,def=1" json:"offlineExpireTime,omitempty"`
	// 透传客户端数据
	Transparent *Transparent `protobuf:"bytes,4,opt,name=transparent" json:"transparent,omitempty"`
	// 透传数据
	ExtraData *string `protobuf:"bytes,5,opt,name=extraData" json:"extraData,omitempty"`
	// 消息类型
	MsgType *int32 `protobuf:"varint,6,opt,name=msgType" json:"msgType,omitempty"`
	// 消息跟踪标志
	MsgTraceFlag *int32 `protobuf:"varint,7,opt,name=msgTraceFlag" json:"msgTraceFlag,omitempty"`
	// 优先级
	Priority         *int32 `protobuf:"varint,8,opt,name=priority" json:"priority,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *OSMessage) Reset()         { *m = OSMessage{} }
func (m *OSMessage) String() string { return proto.CompactTextString(m) }
func (*OSMessage) ProtoMessage()    {}

const Default_OSMessage_OfflineExpireTime int64 = 1

func (m *OSMessage) GetIsOffline() bool {
	if m != nil && m.IsOffline != nil {
		return *m.IsOffline
	}
	return false
}

func (m *OSMessage) GetOfflineExpireTime() int64 {
	if m != nil && m.OfflineExpireTime != nil {
		return *m.OfflineExpireTime
	}
	return Default_OSMessage_OfflineExpireTime
}

func (m *OSMessage) GetTransparent() *Transparent {
	if m != nil {
		return m.Transparent
	}
	return nil
}

func (m *OSMessage) GetExtraData() string {
	if m != nil && m.ExtraData != nil {
		return *m.ExtraData
	}
	return ""
}

func (m *OSMessage) GetMsgType() int32 {
	if m != nil && m.MsgType != nil {
		return *m.MsgType
	}
	return 0
}

func (m *OSMessage) GetMsgTraceFlag() int32 {
	if m != nil && m.MsgTraceFlag != nil {
		return *m.MsgTraceFlag
	}
	return 0
}

func (m *OSMessage) GetPriority() int32 {
	if m != nil && m.Priority != nil {
		return *m.Priority
	}
	return 0
}

// MMP消息
type MMPMessage struct {
	// 动作链数据
	Transparent *Transparent `protobuf:"bytes,2,opt,name=transparent" json:"transparent,omitempty"`
	// 透传数据
	ExtraData *string `protobuf:"bytes,3,opt,name=extraData" json:"extraData,omitempty"`
	// 消息类型
	MsgType *int32 `protobuf:"varint,4,opt,name=msgType" json:"msgType,omitempty"`
	// 消息跟踪标志
	MsgTraceFlag *int32 `protobuf:"varint,5,opt,name=msgTraceFlag" json:"msgTraceFlag,omitempty"`
	// 离线超时时间
	MsgOfflineExpire *int64 `protobuf:"varint,6,opt,name=msgOfflineExpire" json:"msgOfflineExpire,omitempty"`
	IsOffline        *bool  `protobuf:"varint,7,opt,name=isOffline,def=1" json:"isOffline,omitempty"`
	// 优先级
	Priority *int32 `protobuf:"varint,8,opt,name=priority" json:"priority,omitempty"`
	// 保存消息体的cdn地址
	CdnUrl           *string `protobuf:"bytes,9,opt,name=cdnUrl" json:"cdnUrl,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MMPMessage) Reset()         { *m = MMPMessage{} }
func (m *MMPMessage) String() string { return proto.CompactTextString(m) }
func (*MMPMessage) ProtoMessage()    {}

const Default_MMPMessage_IsOffline bool = true

func (m *MMPMessage) GetTransparent() *Transparent {
	if m != nil {
		return m.Transparent
	}
	return nil
}

func (m *MMPMessage) GetExtraData() string {
	if m != nil && m.ExtraData != nil {
		return *m.ExtraData
	}
	return ""
}

func (m *MMPMessage) GetMsgType() int32 {
	if m != nil && m.MsgType != nil {
		return *m.MsgType
	}
	return 0
}

func (m *MMPMessage) GetMsgTraceFlag() int32 {
	if m != nil && m.MsgTraceFlag != nil {
		return *m.MsgTraceFlag
	}
	return 0
}

func (m *MMPMessage) GetMsgOfflineExpire() int64 {
	if m != nil && m.MsgOfflineExpire != nil {
		return *m.MsgOfflineExpire
	}
	return 0
}

func (m *MMPMessage) GetIsOffline() bool {
	if m != nil && m.IsOffline != nil {
		return *m.IsOffline
	}
	return Default_MMPMessage_IsOffline
}

func (m *MMPMessage) GetPriority() int32 {
	if m != nil && m.Priority != nil {
		return *m.Priority
	}
	return 0
}

func (m *MMPMessage) GetCdnUrl() string {
	if m != nil && m.CdnUrl != nil {
		return *m.CdnUrl
	}
	return ""
}

// 透传协议
type Transparent struct {
	// 指令ID
	Id *string `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	// 动作
	Action *string `protobuf:"bytes,2,req,name=action" json:"action,omitempty"`
	// 任务ID
	TaskId *string `protobuf:"bytes,3,req,name=taskId" json:"taskId,omitempty"`
	AppKey *string `protobuf:"bytes,4,req,name=appKey" json:"appKey,omitempty"`
	AppId  *string `protobuf:"bytes,5,req,name=appId" json:"appId,omitempty"`
	// 消息ID
	MessageId *string   `protobuf:"bytes,6,req,name=messageId" json:"messageId,omitempty"`
	PushInfo  *PushInfo `protobuf:"bytes,7,opt,name=pushInfo" json:"pushInfo,omitempty"`
	// 动作链
	ActionChain      []*ActionChain `protobuf:"bytes,8,rep,name=actionChain" json:"actionChain,omitempty"`
	Condition        []string       `protobuf:"bytes,9,rep,name=condition" json:"condition,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *Transparent) Reset()         { *m = Transparent{} }
func (m *Transparent) String() string { return proto.CompactTextString(m) }
func (*Transparent) ProtoMessage()    {}

func (m *Transparent) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Transparent) GetAction() string {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return ""
}

func (m *Transparent) GetTaskId() string {
	if m != nil && m.TaskId != nil {
		return *m.TaskId
	}
	return ""
}

func (m *Transparent) GetAppKey() string {
	if m != nil && m.AppKey != nil {
		return *m.AppKey
	}
	return ""
}

func (m *Transparent) GetAppId() string {
	if m != nil && m.AppId != nil {
		return *m.AppId
	}
	return ""
}

func (m *Transparent) GetMessageId() string {
	if m != nil && m.MessageId != nil {
		return *m.MessageId
	}
	return ""
}

func (m *Transparent) GetPushInfo() *PushInfo {
	if m != nil {
		return m.PushInfo
	}
	return nil
}

func (m *Transparent) GetActionChain() []*ActionChain {
	if m != nil {
		return m.ActionChain
	}
	return nil
}

func (m *Transparent) GetCondition() []string {
	if m != nil {
		return m.Condition
	}
	return nil
}

type PushInfo struct {
	Message          *string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	ActionKey        *string `protobuf:"bytes,2,opt,name=actionKey" json:"actionKey,omitempty"`
	Sound            *string `protobuf:"bytes,3,opt,name=sound" json:"sound,omitempty"`
	Badge            *string `protobuf:"bytes,4,opt,name=badge" json:"badge,omitempty"`
	Payload          *string `protobuf:"bytes,5,opt,name=payload" json:"payload,omitempty"`
	LocKey           *string `protobuf:"bytes,6,opt,name=locKey" json:"locKey,omitempty"`
	LocArgs          *string `protobuf:"bytes,7,opt,name=locArgs" json:"locArgs,omitempty"`
	ActionLocKey     *string `protobuf:"bytes,8,opt,name=actionLocKey" json:"actionLocKey,omitempty"`
	LaunchImage      *string `protobuf:"bytes,9,opt,name=launchImage" json:"launchImage,omitempty"`
	ContentAvailable *int32  `protobuf:"varint,10,opt,name=contentAvailable" json:"contentAvailable,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PushInfo) Reset()         { *m = PushInfo{} }
func (m *PushInfo) String() string { return proto.CompactTextString(m) }
func (*PushInfo) ProtoMessage()    {}

func (m *PushInfo) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *PushInfo) GetActionKey() string {
	if m != nil && m.ActionKey != nil {
		return *m.ActionKey
	}
	return ""
}

func (m *PushInfo) GetSound() string {
	if m != nil && m.Sound != nil {
		return *m.Sound
	}
	return ""
}

func (m *PushInfo) GetBadge() string {
	if m != nil && m.Badge != nil {
		return *m.Badge
	}
	return ""
}

func (m *PushInfo) GetPayload() string {
	if m != nil && m.Payload != nil {
		return *m.Payload
	}
	return ""
}

func (m *PushInfo) GetLocKey() string {
	if m != nil && m.LocKey != nil {
		return *m.LocKey
	}
	return ""
}

func (m *PushInfo) GetLocArgs() string {
	if m != nil && m.LocArgs != nil {
		return *m.LocArgs
	}
	return ""
}

func (m *PushInfo) GetActionLocKey() string {
	if m != nil && m.ActionLocKey != nil {
		return *m.ActionLocKey
	}
	return ""
}

func (m *PushInfo) GetLaunchImage() string {
	if m != nil && m.LaunchImage != nil {
		return *m.LaunchImage
	}
	return ""
}

func (m *PushInfo) GetContentAvailable() int32 {
	if m != nil && m.ContentAvailable != nil {
		return *m.ContentAvailable
	}
	return 0
}

// 动作链
type ActionChain struct {
	ActionId *int32            `protobuf:"varint,1,req,name=actionId" json:"actionId,omitempty"`
	Type     *ActionChain_Type `protobuf:"varint,2,req,name=type,enum=protobuf.ActionChain_Type" json:"type,omitempty"`
	Next     *int32            `protobuf:"varint,3,opt,name=next" json:"next,omitempty"`
	// notification
	Logo    *string `protobuf:"bytes,100,opt,name=logo" json:"logo,omitempty"`
	LogoURL *string `protobuf:"bytes,101,opt,name=logoURL" json:"logoURL,omitempty"`
	Title   *string `protobuf:"bytes,102,opt,name=title" json:"title,omitempty"`
	Text    *string `protobuf:"bytes,103,opt,name=text" json:"text,omitempty"`
	// 是否可清除
	Clearable *bool `protobuf:"varint,104,opt,name=clearable" json:"clearable,omitempty"`
	// 是否振铃
	Ring *bool `protobuf:"varint,105,opt,name=ring" json:"ring,omitempty"`
	// 是否震动
	Buzz *bool `protobuf:"varint,106,opt,name=buzz" json:"buzz,omitempty"`
	// 通过url方式指定动态banner图片作为通知背景图，通栏显示
	BannerURL *string `protobuf:"bytes,107,opt,name=bannerURL" json:"bannerURL,omitempty"`
	// Popup
	Img     *string   `protobuf:"bytes,120,opt,name=img" json:"img,omitempty"`
	Buttons []*Button `protobuf:"bytes,121,rep,name=buttons" json:"buttons,omitempty"`
	// Startapp
	Appid        *string     `protobuf:"bytes,140,opt,name=appid" json:"appid,omitempty"`
	Appstartupid *AppStartUp `protobuf:"bytes,141,opt,name=appstartupid" json:"appstartupid,omitempty"`
	// 对于Android平台， 是否通过startActivity自动启动相应app
	Autostart *bool `protobuf:"varint,142,opt,name=autostart" json:"autostart,omitempty"`
	// 启动失败动作
	FailedAction *int32 `protobuf:"varint,143,opt,name=failedAction" json:"failedAction,omitempty"`
	// Startweb
	Url *string `protobuf:"bytes,160,opt,name=url" json:"url,omitempty"`
	// 访问地址时，是否需要包含cid信息
	Withcid *string `protobuf:"bytes,161,opt,name=withcid" json:"withcid,omitempty"`
	// is_withnettype：（可选，默认false）
	IsWithnettype *bool `protobuf:"varint,162,opt,name=is_withnettype,def=0" json:"is_withnettype,omitempty"`
	// SmsInbox
	// 发件人地址
	Address *string `protobuf:"bytes,180,opt,name=address" json:"address,omitempty"`
	// 短信内容
	Content *string `protobuf:"bytes,181,opt,name=content" json:"content,omitempty"`
	// 短信创建时间，默认为手机当前时间
	Ct *int64 `protobuf:"varint,182,opt,name=ct" json:"ct,omitempty"`
	// 短信状态
	Flag *SMSStatus `protobuf:"varint,183,opt,name=flag,enum=protobuf.SMSStatus" json:"flag,omitempty"`
	// CheckApp
	SuccessedAction   *int32 `protobuf:"varint,200,opt,name=successedAction" json:"successedAction,omitempty"`
	UninstalledAction *int32 `protobuf:"varint,201,opt,name=uninstalledAction" json:"uninstalledAction,omitempty"`
	// AppDownload
	// 资源名称，用于Android通知栏提示文案，如“正在下载xxx…”、“xxx下载已完成，点击安装”
	Name *string `protobuf:"bytes,220,opt,name=name" json:"name,omitempty"`
	// 下载完成后是否自动启动安装
	AutoInstall *bool `protobuf:"varint,223,opt,name=autoInstall" json:"autoInstall,omitempty"`
	// wifi环境下是否自动下载安装包
	WifiAutodownload *bool `protobuf:"varint,225,opt,name=wifiAutodownload" json:"wifiAutodownload,omitempty"`
	// 是否强制下载（默认会自动下载完成，即使用户点击清除按钮）
	ForceDownload *bool `protobuf:"varint,226,opt,name=forceDownload" json:"forceDownload,omitempty"`
	// 是否显示下载进度
	ShowProgress *bool `protobuf:"varint,227,opt,name=showProgress" json:"showProgress,omitempty"`
	// HttpProxy
	// HTTP POST data
	Post *string `protobuf:"bytes,241,opt,name=post" json:"post,omitempty"`
	// http自定义头信息
	Headers *string `protobuf:"bytes,242,opt,name=headers" json:"headers,omitempty"`
	// SmsInbox2
	// ----- 以下参数仅AndroidSDK需要处理 ----
	// 该次通知栏提示是否支持合并组。支持组合并的短信/彩信，在Android上通知呈现需要进行合并。
	Groupable *bool `protobuf:"varint,260,opt,name=groupable" json:"groupable,omitempty"`
	// MmsInbox2
	// 彩信标题
	MmsTitle *string `protobuf:"bytes,280,opt,name=mmsTitle" json:"mmsTitle,omitempty"`
	// 彩信包资源地址
	MmsURL *string `protobuf:"bytes,281,opt,name=mmsURL" json:"mmsURL,omitempty"`
	// Popupweb
	// 是否需要做网页本地预载，如果为true，SDK负责预先下载网页所需的html、css、js、img等资源文件，下载完成后统一显示
	Preload *bool `protobuf:"varint,300,opt,name=preload" json:"preload,omitempty"`
	// terminatetask
	// 终止指定的taskid的动作执行，尽可能回滚已执行的动作。
	Taskid *string `protobuf:"bytes,320,opt,name=taskid" json:"taskid,omitempty"`
	// enablelog
	// 日志开启持续时间，单位s
	Duration *int64 `protobuf:"varint,340,opt,name=duration" json:"duration,omitempty"`
	// uploadlog
	// date：（必填）日志日期，格式为YYYYMMDD
	Date             *string `protobuf:"bytes,360,opt,name=date" json:"date,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ActionChain) Reset()         { *m = ActionChain{} }
func (m *ActionChain) String() string { return proto.CompactTextString(m) }
func (*ActionChain) ProtoMessage()    {}

const Default_ActionChain_IsWithnettype bool = false

func (m *ActionChain) GetActionId() int32 {
	if m != nil && m.ActionId != nil {
		return *m.ActionId
	}
	return 0
}

func (m *ActionChain) GetType() ActionChain_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ActionChain_Goto
}

func (m *ActionChain) GetNext() int32 {
	if m != nil && m.Next != nil {
		return *m.Next
	}
	return 0
}

func (m *ActionChain) GetLogo() string {
	if m != nil && m.Logo != nil {
		return *m.Logo
	}
	return ""
}

func (m *ActionChain) GetLogoURL() string {
	if m != nil && m.LogoURL != nil {
		return *m.LogoURL
	}
	return ""
}

func (m *ActionChain) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *ActionChain) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

func (m *ActionChain) GetClearable() bool {
	if m != nil && m.Clearable != nil {
		return *m.Clearable
	}
	return false
}

func (m *ActionChain) GetRing() bool {
	if m != nil && m.Ring != nil {
		return *m.Ring
	}
	return false
}

func (m *ActionChain) GetBuzz() bool {
	if m != nil && m.Buzz != nil {
		return *m.Buzz
	}
	return false
}

func (m *ActionChain) GetBannerURL() string {
	if m != nil && m.BannerURL != nil {
		return *m.BannerURL
	}
	return ""
}

func (m *ActionChain) GetImg() string {
	if m != nil && m.Img != nil {
		return *m.Img
	}
	return ""
}

func (m *ActionChain) GetButtons() []*Button {
	if m != nil {
		return m.Buttons
	}
	return nil
}

func (m *ActionChain) GetAppid() string {
	if m != nil && m.Appid != nil {
		return *m.Appid
	}
	return ""
}

func (m *ActionChain) GetAppstartupid() *AppStartUp {
	if m != nil {
		return m.Appstartupid
	}
	return nil
}

func (m *ActionChain) GetAutostart() bool {
	if m != nil && m.Autostart != nil {
		return *m.Autostart
	}
	return false
}

func (m *ActionChain) GetFailedAction() int32 {
	if m != nil && m.FailedAction != nil {
		return *m.FailedAction
	}
	return 0
}

func (m *ActionChain) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *ActionChain) GetWithcid() string {
	if m != nil && m.Withcid != nil {
		return *m.Withcid
	}
	return ""
}

func (m *ActionChain) GetIsWithnettype() bool {
	if m != nil && m.IsWithnettype != nil {
		return *m.IsWithnettype
	}
	return Default_ActionChain_IsWithnettype
}

func (m *ActionChain) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

func (m *ActionChain) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func (m *ActionChain) GetCt() int64 {
	if m != nil && m.Ct != nil {
		return *m.Ct
	}
	return 0
}

func (m *ActionChain) GetFlag() SMSStatus {
	if m != nil && m.Flag != nil {
		return *m.Flag
	}
	return SMSStatus_unread
}

func (m *ActionChain) GetSuccessedAction() int32 {
	if m != nil && m.SuccessedAction != nil {
		return *m.SuccessedAction
	}
	return 0
}

func (m *ActionChain) GetUninstalledAction() int32 {
	if m != nil && m.UninstalledAction != nil {
		return *m.UninstalledAction
	}
	return 0
}

func (m *ActionChain) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ActionChain) GetAutoInstall() bool {
	if m != nil && m.AutoInstall != nil {
		return *m.AutoInstall
	}
	return false
}

func (m *ActionChain) GetWifiAutodownload() bool {
	if m != nil && m.WifiAutodownload != nil {
		return *m.WifiAutodownload
	}
	return false
}

func (m *ActionChain) GetForceDownload() bool {
	if m != nil && m.ForceDownload != nil {
		return *m.ForceDownload
	}
	return false
}

func (m *ActionChain) GetShowProgress() bool {
	if m != nil && m.ShowProgress != nil {
		return *m.ShowProgress
	}
	return false
}

func (m *ActionChain) GetPost() string {
	if m != nil && m.Post != nil {
		return *m.Post
	}
	return ""
}

func (m *ActionChain) GetHeaders() string {
	if m != nil && m.Headers != nil {
		return *m.Headers
	}
	return ""
}

func (m *ActionChain) GetGroupable() bool {
	if m != nil && m.Groupable != nil {
		return *m.Groupable
	}
	return false
}

func (m *ActionChain) GetMmsTitle() string {
	if m != nil && m.MmsTitle != nil {
		return *m.MmsTitle
	}
	return ""
}

func (m *ActionChain) GetMmsURL() string {
	if m != nil && m.MmsURL != nil {
		return *m.MmsURL
	}
	return ""
}

func (m *ActionChain) GetPreload() bool {
	if m != nil && m.Preload != nil {
		return *m.Preload
	}
	return false
}

func (m *ActionChain) GetTaskid() string {
	if m != nil && m.Taskid != nil {
		return *m.Taskid
	}
	return ""
}

func (m *ActionChain) GetDuration() int64 {
	if m != nil && m.Duration != nil {
		return *m.Duration
	}
	return 0
}

func (m *ActionChain) GetDate() string {
	if m != nil && m.Date != nil {
		return *m.Date
	}
	return ""
}

type AppStartUp struct {
	Android          *string `protobuf:"bytes,1,opt,name=android" json:"android,omitempty"`
	Symbia           *string `protobuf:"bytes,2,opt,name=symbia" json:"symbia,omitempty"`
	Ios              *string `protobuf:"bytes,3,opt,name=ios" json:"ios,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AppStartUp) Reset()         { *m = AppStartUp{} }
func (m *AppStartUp) String() string { return proto.CompactTextString(m) }
func (*AppStartUp) ProtoMessage()    {}

func (m *AppStartUp) GetAndroid() string {
	if m != nil && m.Android != nil {
		return *m.Android
	}
	return ""
}

func (m *AppStartUp) GetSymbia() string {
	if m != nil && m.Symbia != nil {
		return *m.Symbia
	}
	return ""
}

func (m *AppStartUp) GetIos() string {
	if m != nil && m.Ios != nil {
		return *m.Ios
	}
	return ""
}

type Button struct {
	Text             *string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
	Next             *int32  `protobuf:"varint,2,opt,name=next" json:"next,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Button) Reset()         { *m = Button{} }
func (m *Button) String() string { return proto.CompactTextString(m) }
func (*Button) ProtoMessage()    {}

func (m *Button) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

func (m *Button) GetNext() int32 {
	if m != nil && m.Next != nil {
		return *m.Next
	}
	return 0
}

type Target struct {
	AppId            *string `protobuf:"bytes,1,req,name=appId" json:"appId,omitempty"`
	ClientId         *string `protobuf:"bytes,2,req,name=clientId" json:"clientId,omitempty"`
	Alias            *string `protobuf:"bytes,3,opt,name=alias" json:"alias,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Target) Reset()         { *m = Target{} }
func (m *Target) String() string { return proto.CompactTextString(m) }
func (*Target) ProtoMessage()    {}

func (m *Target) GetAppId() string {
	if m != nil && m.AppId != nil {
		return *m.AppId
	}
	return ""
}

func (m *Target) GetClientId() string {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return ""
}

func (m *Target) GetAlias() string {
	if m != nil && m.Alias != nil {
		return *m.Alias
	}
	return ""
}

func init() {
	proto.RegisterEnum("protobuf.CmdID", CmdID_name, CmdID_value)
	proto.RegisterEnum("protobuf.SMSStatus", SMSStatus_name, SMSStatus_value)
	proto.RegisterEnum("protobuf.GtAuthResult_GtAuthResultCode", GtAuthResult_GtAuthResultCode_name, GtAuthResult_GtAuthResultCode_value)
	proto.RegisterEnum("protobuf.ReqServListResult_ReqServHostResultCode", ReqServListResult_ReqServHostResultCode_name, ReqServListResult_ReqServHostResultCode_value)
	proto.RegisterEnum("protobuf.PushResult_EPushResult", PushResult_EPushResult_name, PushResult_EPushResult_value)
	proto.RegisterEnum("protobuf.ServerNotify_NotifyType", ServerNotify_NotifyType_name, ServerNotify_NotifyType_value)
	proto.RegisterEnum("protobuf.ActionChain_Type", ActionChain_Type_name, ActionChain_Type_value)
}
